- build: examples/1-get-values-DiagnosticsHelperRK
  photon: [0.8.0-rc.12, 1.0.0]
  p1: [1.0.0]
  electron: [0.8.0-rc.12, 1.0.0]
  argon: [0.8.0-rc.27]
  boron: [0.8.0-rc.27]
  xenon: [0.8.0-rc.27]
- build: examples/2-get-json-DiagnosticsHelperRK
  electron: [1.0.0]
  boron: [0.8.0-rc.27]
- build: examples/3-powered-by-DiagnosticsHelperRK
  electron: [1.0.0]
  boron: [0.8.0-rc.27]
